#!/bin/sh

mysql -uroot -pJZworkb0x << FLAG
set FOREIGN_KEY_CHECKS=0;

CREATE DATABASE IF NOT EXISTS payFrameWork;
CREATE DATABASE IF NOT EXISTS payShared;
CREATE DATABASE IF NOT EXISTS payBranch;

GRANT ALL PRIVILEGES ON payFrameWork.* TO 'mycoz'@'localhost' IDENTIFIED BY 'xmlpj0#' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON payShared.* TO 'mycoz'@'localhost' IDENTIFIED BY 'xmlpj0#' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON payBranch.* TO 'mycoz'@'localhost' IDENTIFIED BY 'xmlpj0#' WITH GRANT OPTION;

#GRANT ALL PRIVILEGES ON payFrameWork.* TO 'mycoz'@'%' IDENTIFIED BY 'xmlpj0#' WITH GRANT OPTION;
#GRANT ALL PRIVILEGES ON payShared.* TO 'mycoz'@'%' IDENTIFIED BY 'xmlpj0#' WITH GRANT OPTION;
#GRANT ALL PRIVILEGES ON payBranch.* TO 'mycoz'@'%' IDENTIFIED BY 'xmlpj0#' WITH GRANT OPTION;

#DROP USER 'mycoz'@'localhost';
#DROP USER 'mycoz'@'%';

FLUSH PRIVILEGES;
set FOREIGN_KEY_CHECKS=1;
FLAG
