SET FOREIGN_KEY_CHECKS = 0;

//Pay System Database Version1.0
CREATE TABLE `Client` (
  `id` int(11) NOT NULL DEFAULT '0',
  `clientName` varchar(16) DEFAULT NULL,
  `idNo` varchar(20) DEFAULT NULL,
  `idEndDate` date DEFAULT NULL,
  `idValidDate` char(1) DEFAULT 'N',
  `idAuthority` varchar(64) DEFAULT NULL,
  `otherNo` varchar(64) DEFAULT NULL,
  `age` int(11) DEFAULT NULL,
   `mobilePhone` varchar(11) DEFAULT NULL,
   `mobileAddress` varchar(32) DEFAULT NULL,
  `sex` varchar(2) DEFAULT NULL,
  `marry` varchar(2) DEFAULT NULL,
  `childs` int(11) DEFAULT NULL,
  `housing` varchar(11) DEFAULT NULL,
  `educationId` int(11) DEFAULT NULL,
  `homePhoneName` varchar(16) DEFAULT NULL,
  `homePhone` varchar(11) DEFAULT NULL,
  `telePhone` varchar(11) DEFAULT NULL,
  `email` varchar(16) DEFAULT NULL,

  `spuseName` varchar(16) DEFAULT NULL,
  `spuseMobile` varchar(11) DEFAULT NULL,
  `idSpuse` varchar(20) DEFAULT NULL,
  `spuseHirer` varchar(16) DEFAULT NULL,
  `spuseOfficePhone` varchar(11) DEFAULT NULL,
  `spuseExtPhone` varchar(11) DEFAULT NULL,
  
  `censusAddressBookId` int(11) NOT NULL DEFAULT '0',
  `livingAddressBookId` int(11) NOT NULL DEFAULT '0',

  `homeName` varchar(16) DEFAULT NULL,
  `homeType` varchar(16) DEFAULT NULL,
  `homeTelephone` varchar(11) DEFAULT NULL,
  `homeAddressBookId` int(11) NOT NULL DEFAULT '0',
  
  `otherContacts` varchar(16) DEFAULT NULL,
  `otherNexus` varchar(16) DEFAULT NULL,
  `otherPhone` varchar(16) DEFAULT NULL,
  
  `masterInMonth` decimal(7,2) DEFAULT NULL,
  `otherInMonth` decimal(7,2) DEFAULT NULL,
  `homeInMonth` decimal(7,2) DEFAULT NULL,
  `otherIncome` decimal(7,2) DEFAULT NULL,
  
  `onShortName` varchar(32) DEFAULT NULL,
  `onFullName` varchar(32) DEFAULT NULL,
  `onDivision` varchar(32) DEFAULT NULL,
  `onCompanyName` varchar(32) DEFAULT NULL,
  `onWorkTime` varchar(32) DEFAULT NULL,
  `onSector` varchar(32) DEFAULT NULL,
  `onOffice` varchar(32) DEFAULT NULL,
  `onFeature` varchar(32) DEFAULT NULL,
  `onOfficePhone` varchar(11) DEFAULT NULL,
  `onExtPhone` varchar(11) DEFAULT NULL,
  `officeAddressBookId` int(11) NOT NULL DEFAULT '0',
  
  `financeName` varchar(16) DEFAULT NULL,
  `saleAmount` decimal(7,2) DEFAULT NULL,
  `selfAmount` decimal(7,2) DEFAULT NULL,
  
  `branchId` int(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `idNo` (`idNo`),
  KEY `mobilePhone` (`mobilePhone`),
  KEY `housing` (`housing`),
  KEY `educationId` (`educationId`),
  KEY `censusAddressBookId` (`censusAddressBookId`),
  KEY `livingAddressBookId` (`livingAddressBookId`),
  KEY `homeAddressBookId` (`homeAddressBookId`),
  KEY `officeAddressBookId` (`officeAddressBookId`),
  KEY `branchId` (`branchId`),
  CONSTRAINT `Client_ibfk_1` FOREIGN KEY (`censusAddressBookId`) REFERENCES `AdressBook` (`id`),
  CONSTRAINT `Client_ibfk_2` FOREIGN KEY (`livingAddressBookId`) REFERENCES `AdressBook` (`id`),
  CONSTRAINT `Client_ibfk_3` FOREIGN KEY (`homeAddressBookId`) REFERENCES `AdressBook` (`id`),
  CONSTRAINT `Client_ibfk_4` FOREIGN KEY (`officeAddressBookId`) REFERENCES `AdressBook` (`id`),
  CONSTRAINT `Client_ibfk_5` FOREIGN KEY (`branchId`) REFERENCES `payShared`.`Branch` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;